[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ortoa-benchmarking"
version = "0.0.1"
readme = "README.md"

dependencies = [
    "pydantic",
]

optional-dependencies.testing = [
    "pytest==7.2.0",
    "pytest-mock",
]
