/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class site_ycsb_db_WaffleClient */

#ifndef _Included_site_ycsb_db_WaffleClient
#define _Included_site_ycsb_db_WaffleClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     site_ycsb_db_WaffleClient
 * Method:    nativeInit
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_WaffleClient_nativeInit
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     site_ycsb_db_WaffleClient
 * Method:    nativeCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_site_ycsb_db_WaffleClient_nativeCleanup
  (JNIEnv *, jobject);

/*
 * Class:     site_ycsb_db_WaffleClient
 * Method:    nativeCreate
 * Signature: (Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_WaffleClient_nativeCreate
  (JNIEnv *, jobject, jstring, jbyteArray);

/*
 * Class:     site_ycsb_db_WaffleClient
 * Method:    nativeRead
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_site_ycsb_db_WaffleClient_nativeRead
  (JNIEnv *, jobject, jstring);

/*
 * Class:     site_ycsb_db_WaffleClient
 * Method:    nativeUpdate
 * Signature: (Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_site_ycsb_db_WaffleClient_nativeUpdate
  (JNIEnv *, jobject, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
